### ISSUE TITLE
Error when applying a Pre-trained Model

### ISSUE THREAD

**Issue by whj363636** [junyanz/CycleGAN#15]
Hi, I follow 'Apply a Pre-trained Model' steps in readme and run `DATA_ROOT=./datasets/ae_photos name=style_cezanne_pretrained model=one_direction_test phase=test loadSize=256 fineSize=256 resize_or_crop="scale_width" th test.lua` in GPU mode , then the error happens:

`THCudaCheck FAIL file=/home/whj/torch/extra/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
/home/whj/torch/install/bin/luajit: /home/whj/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 29 module of nn.Sequential:
/home/whj/torch/install/share/lua/5.1/nn/THNN.lua:110: cuda runtime error (2) : out of memory at /home/whj/torch/extra/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
	[C]: in function 'v'
	/home/whj/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'SpatialConvolutionMM_updateOutput'
	...hj/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:79: in function <...hj/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:76>
	[C]: in function 'xpcall'
	/home/whj/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/whj/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	./models/one_direction_test_model.lua:44: in function 'Forward'
	test.lua:101: in main chunk
	[C]: in function 'dofile'
	.../whj/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/home/whj/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/home/whj/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	./models/one_direction_test_model.lua:44: in function 'Forward'
	test.lua:101: in main chunk
	[C]: in function 'dofile'
	.../whj/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
`

**Comment by gforsyth** [comment]
Hey @whj363636 -- this thing is pretty memory hungry -- the `fineSize` parameter determines the dimensions of the output images -- you can try to drop it down to 128 and see if that works?

**Comment by junyanz** [comment]
What's the size of your GPU memory? You can also try it in CPU mode.

**Comment by whj363636** [comment]
@junyanz 
Hi, Thanks for replying
My GPU memory is 2002MiB and it is 840M, I follow @gforsyth 's advice and it works in GPU mode, but when I set `gpu=0 cudnn=0` and run the code again, but the error happens:
`CPU Mode	
function: 0x400a3a90	
DataLoader UnalignedDataLoader was created.	
Starting donkey with id: 1 seed: 7867
table: 0x4151daf0
table: 0x416cbc88
running "find" on each class directory, and concatenate all those filenames into a single file containing all image paths for a given class
now combine all the files to a single large file
load the large concatenated list of sample paths to self.imagePath
cmd..wc -L '/tmp/lua_VSvyIt' |cut -f1 -d' '
205 samples found.... 0/205 ....................] ETA: 0ms | Step: 0ms          
Updating classList and imageClass appropriately
 [=================== 1/1 =====================>] Tot: 0ms | Step: 0ms          
Cleaning up temporary files
Dataset Size A: 	205	
Starting donkey with id: 1 seed: 620
table: 0x402b5310
table: 0x41bf3ee8
running "find" on each class directory, and concatenate all those filenames into a single file containing all image paths for a given class
now combine all the files to a single large file
load the large concatenated list of sample paths to self.imagePath
cmd..wc -L '/tmp/lua_kH652n' |cut -f1 -d' '
205 samples found.... 0/205 ....................] ETA: 0ms | Step: 0ms          
Updating classList and imageClass appropriately
 [=================== 1/1 =====================>] Tot: 0ms | Step: 0ms          
Cleaning up temporary files
Dataset Size B: 	205	
use InstanceNormalization	
loading previously trained model (/home/whj/CycleGAN/checkpoints/style_cezanne_pretrained/latest_net_G.t7)	
use InstanceNormalization	
/home/whj/torch/install/bin/luajit: /home/whj/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <torch.CudaTensor>
stack traceback:
	[C]: in function 'error'
	/home/whj/torch/install/share/lua/5.1/torch/File.lua:343: in function 'readObject'
	/home/whj/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/whj/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	/home/whj/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/home/whj/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	/home/whj/CycleGAN/util/util.lua:192: in function 'load_test_model'
	./models/one_direction_test_model.lua:23: in function 'Initialize'
	test.lua:80: in main chunk
	[C]: in function 'dofile'
	.../whj/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
`

**Comment by whj363636** [comment]
@gforsyth It works! Thank you very much:)

**Comment by taesung89** [comment]
For the CUDNN error, could you try the suggested method in [this issue](https://github.com/junyanz/CycleGAN/issues/12)?

**Comment by whj363636** [comment]
@taesung89 Thanks, it fixes my problem in pretrained model. But horse2zebra example in GPU mode it still fails as I said to @gforsyth . I also try CPU mode, it works but too slow. So any advice for that?

**Comment by whj363636** [comment]
I fixed it. Thanks for all of you

**Comment by aaronlinsky** [comment]
@whj363636 I'm getting the same error while using GPU mode. How did you fix your error?

**Comment by whj363636** [comment]
@aaronlinsky Two way to deal with it, one is to use CPU mode like others suggest if you just want to see the result and aren't worried about the time, another is to lower the `fineSize`. The latter one solves my problem, you can have a try :)

**Comment by storming15** [comment]
ayudenme a mi me sale un mesaje de error de error stack traceback: setup line: 1 in main chunk
